volumes:
    DONT-KICK-THE-BUCKET:
        external: true
    postgres-data:
        external: true
services:

    postgres:
        build:
            context: ./db
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=users, parks
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    users:
        build:
            context: ./users
            dockerfile: ./Dockerfile.dev
        ports:
            - "8090:8000"
        volumes:
            - ./users:/app
        environment:
            DATABASE_URL: postgresql://users:password@postgres/users
            WAIT_HOSTS: postgres:5432
    parks:
        build:
            context: ./parks
            dockerfile: ./Dockerfile.dev
        ports:
            - "8080:8000"
        volumes:
            - ./parks:/app
        environment:
            DATABASE_URL: postgresql://parks:password@postgres/parks
            WAIT_HOSTS: postgres:5432
            NPS_API_KEY: ${NPS_API_KEY}
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_USERS: http://localhost:8090
            REACT_APP_PARKS: http://localhost:8080
