volumes:
    DONT-KICK-THE-BUCKET:
        external: true
    postgres-data:
        external: true
services:

    postgres:
        image: postgres:14.2-bullseye        
        volumes:
            - postgres-data:/var/lib/postgres/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=users, parks
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    users:
        build:
            context: ./users
            dockerfile: ./Dockerfile.dev
        ports:
            - "8090:8000"
        volumes:
            - ./users:/app
        environment:
            DATABASE_URL: postgres://users:password@postgres/users
            WAIT_HOSTS: postgres:5432
    parks:
        build:
            context: ./parks
            dockerfile: ./Dockerfile.dev
        ports:
            - "8080:8000"
        volumes:
            - ./parks:/app
        environment:
            DATABASE_URL: postgres://parks:password@postgres/parks
            WAIT_HOSTS: postgres:5432
            NPS_API_KEY: ${NPS_API_KEY}
    parks-poller:        
        build:
            context: ./parks/poll
            dockerfile: ./Dockerfile.dev
        volumes:
            - ./parks/poll:/app
            - ./parks/parks_project:/app/parks_project
            - ./parks/parks_rest:/app/parks_rest
        depends_on:
            - postgres
            - parks
        environment:
            DATABASE_URL: postgres://parks:password@database:5432/parks
            WAIT_HOSTS: database:5432,parks:8000
            WAIT_TIMEOUT: 240
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_USERS: http://localhost:8090
            REACT_APP_PARKS: http://localhost:8080
